### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by qdinfish** [ruiyan1995/Group-Activity-Recognition#4]
Hi, I got following issue when run "Activity.evaluate", please help have a look.

/home/Group-Activity-Recognition-1/Solver.py:111: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  probs = F.softmax(outputs.data)
Traceback (most recent call last):
  File "GAR.py", line 54, in <module>
  File "/home/Group-Activity-Recognition-1/Runtime/Activity_Level.py", line 19, in evaluate
  File "/home/Group-Activity-Recognition-1/Solver.py", line 106, in evaluate
  File "/root/miniconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 576, in __next__
  File "/root/miniconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch
  File "/root/miniconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
  File "/root/miniconda2/lib/python2.7/multiprocessing/queues.py", line 135, in get
  File "/root/miniconda2/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 22, in recv
  File "/root/miniconda2/lib/python2.7/pickle.py", line 1388, in loads
  File "/root/miniconda2/lib/python2.7/pickle.py", line 864, in load
  File "/root/miniconda2/lib/python2.7/pickle.py", line 1139, in load_reduce
  File "/root/miniconda2/lib/python2.7/site-packages/torch/multiprocessing/reductions.py", line 274, in rebuild_storage_fd
  File "/root/miniconda2/lib/python2.7/multiprocessing/reduction.py", line 155, in rebuild_handle
  File "/root/miniconda2/lib/python2.7/multiprocessing/connection.py", line 169, in Client
  File "/root/miniconda2/lib/python2.7/multiprocessing/connection.py", line 320, in SocketClient
OSError: [Errno 24] Too many open files

**Comment by ruiyan1995** [comment]
> Hi, I got following issue when run "Activity.evaluate", please help have a look.
> 
> /home/Group-Activity-Recognition-1/Solver.py:111: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
> probs = F.softmax(outputs.data)
> Traceback (most recent call last):
> File "GAR.py", line 54, in 
> File "/home/Group-Activity-Recognition-1/Runtime/Activity_Level.py", line 19, in evaluate
> File "/home/Group-Activity-Recognition-1/Solver.py", line 106, in evaluate
> File "/root/miniconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 576, in **next**
> File "/root/miniconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch
> File "/root/miniconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
> File "/root/miniconda2/lib/python2.7/multiprocessing/queues.py", line 135, in get
> File "/root/miniconda2/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 22, in recv
> File "/root/miniconda2/lib/python2.7/pickle.py", line 1388, in loads
> File "/root/miniconda2/lib/python2.7/pickle.py", line 864, in load
> File "/root/miniconda2/lib/python2.7/pickle.py", line 1139, in load_reduce
> File "/root/miniconda2/lib/python2.7/site-packages/torch/multiprocessing/reductions.py", line 274, in rebuild_storage_fd
> File "/root/miniconda2/lib/python2.7/multiprocessing/reduction.py", line 155, in rebuild_handle
> File "/root/miniconda2/lib/python2.7/multiprocessing/connection.py", line 169, in Client
> File "/root/miniconda2/lib/python2.7/multiprocessing/connection.py", line 320, in SocketClient
> OSError: [Errno 24] Too many open files

It's a system error! Just type the command "ulimit -n 4096"!
