### ISSUE TITLE
SOME ERROR IN NEW VERSION

### ISSUE THREAD

**Issue by NaifahNurya** [ruiyan1995/Group-Activity-Recognition#8]
I tested the new version of the code it gives the following errors; i seems the test & train_val files are created but fails to be written. it means the file are created but it is empty. 

The following are what i got,

I tested the code on VD dataset.

Epoch 0/14
----------
Traceback (most recent call last):
  File "GAR.py", line 34, in <module>
    Action.trainval()
  File "C:\Users\GAR3\Runtime\Piplines.py", line 60, in trainval
    self.solver.train_model()
  File "C:\Users\GAR3\Solver.py", line 96, in train_model
    epoch_loss = float(self.running_loss) /(self.data_sizes[phase])
ZeroDivisionError: float division by zero

_**ZeroDivisionError due to nothing on data_sizes[phase], because the file traival is empty**_

Any idea on how to clear this??
![Error](https://user-images.githubusercontent.com/41193844/64071196-63f73800-ccaf-11e9-9c66-303317a9169b.JPG)

**Comment by ruiyan1995** [comment]
The directory structure of 'imgs_ranked' should be the same as 'imgs'. I'm confused about the folder of 'dataset'.

**Comment by NaifahNurya** [comment]
The directory structure looks as follows:

VD then in the VD there  are three folders i.e  imgs, video and imgs_ranked. Then when you enter into the imgs_ranked folder  there are  dataset folder and other four files as shown in the attachment above.

**Comment by ruiyan1995** [comment]
> The directory structure looks as follows:
> 
> VD then in the VD there are three folders i.e imgs, video and imgs_ranked. Then when you enter into the imgs_ranked folder there are dataset folder and other four files as shown in the attachment above.

Did it run successfully?

**Comment by NaifahNurya** [comment]
Yes, it runs successfully. Sorry for the late reply, I was far from access to my PC.
